name: Kosli Attest Veracode scan vulnerability summary

# Attest veracode scan vulnerability summary
#   https://docs.kosli.com/client_reference/kosli_attest_custom/


inputs:
  # The Following environment variables must be set in your GitHub action
  # before using this composite
  # env:
  #   KOSLI_ORG: kosli
  #   KOSLI_API_TOKEN: "${{ secrets.KOSLI_API_TOKEN }}"
  #   KOSLI_CLI_VERSION: 2.11.6
  kosli-flow:
    description: "Kosli flow for veracode summary scanning"
    required: true
  kosli-trail-base-name:
    description: "Kosli trail base-name for veracode summary scanning. Often something generic like 'frontend'"
    required: true
  kosli-attestation-template-name:
    description: "Name of the attestation in kosli template-file. Often something generic like 'security-scan-vulnerability-summary'"
    required: true
  veracode-scan-results-file:
    description: "Veracode scan results file. Output from 'veracode static scan --results-file=xxx.json"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Kosli cli
      uses: kosli-dev/setup-cli-action@v2
      with:
        version:
          ${{ env.KOSLI_CLI_VERSION }}

    - name: Create veracode summary
      run: ./scripts/create-veracode-summary-file.sh ${{ inputs.veracode-scan-results-file }} summary-${{ inputs.veracode-scan-results-file }}

    - name: Attest Veracode scan vulnerability summary
      shell: bash
      run: |
        # In this example we use a fiscal year for the compliance period
        # This can also be a normal year or maybe a IS027001 period going
        # from 5th of september one year to the next. Pick what is best for you
        FISCAL_YEAR=$(date -d "+6 months" +%y)
        TRAIL_NAME="FY-${FISCAL_YEAR}-${{ inputs.kosli-trail-base-name }}"
        kosli attest custom \
          --type=veracode-scan-vulnerability-summary \
          --flow ${{ inputs.kosli-flow }} \
          --trail ${TRAIL_NAME} \
          --name ${{ inputs.kosli-attestation-template-name }} \
          --attestation-data summary-${{ inputs.veracode-scan-results-file }}
