name: Kosli Attest Veracode scan executed

# Attest veracode executed
#   https://docs.kosli.com/client_reference/kosli_attest_custom/

inputs:
  # The Following environment variables must be set in your GitHub action
  # before using this composite
  # env:
  #   KOSLI_ORG: kosli
  #   KOSLI_FLOW: your-flow-name
  #   KOSLI_TRAIL: your-trail-name (often git-commit-sha)
  #   KOSLI_API_TOKEN: "${{ secrets.KOSLI_API_TOKEN }}" 
  #   KOSLI_CLI_VERSION: 2.11.6
  kosli-attestation-template-name:
    description: "Name of the attestation in kosli template-file. Often something generic like 'security-scan-executed'"
    required: true
  artifact-fingerprint:
    description: "Fingerprint of artifact (must specify this or the kosli-artifact-template-name)"
    required: false
  kosli-artifact-template-name:
    description: "Name of the artifact in kosli template-file. Often something generic like 'frontend'"
    required: false
  veracode-scan-results-file:
    description: "Veracode scan results file. Output from 'veracode static scan --results-file=xxx.json"
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.artifact-fingerprint }}" && -z "${{ inputs.kosli-artifact-template-name }}" ]]; then
          echo "Error: You must specify either artifact-fingerprint or kosli-artifact-template-name."
          exit 1
        fi

    - name: Setup Kosli cli
      uses: kosli-dev/setup-cli-action@v2
      with:
        version:
          ${{ env.KOSLI_CLI_VERSION }}

    - name: Create veracode summary
      shell: bash
      run: ./scripts/create-veracode-summary-file.sh ${{ inputs.veracode-scan-results-file }} summary-${{ inputs.veracode-scan-results-file }}

    - name: Attest Veracode scan executed
      shell: bash
      run: |
        if [ -n "${{ inputs.artifact-fingerprint }}" ]; then
          kosli attest custom \
            --type=veracode-scan-executed \
            --name ${{ inputs.kosli-attestation-template-name }} \
            --fingerprint ${{ inputs.artifact-fingerprint }} \
            --attestation-data summary-${{ inputs.veracode-scan-results-file }}
        else
           kosli attest custom \
            --type=veracode-scan-executed \
            --name ${{ inputs.kosli-artifact-template-name }}.${{ inputs.kosli-attestation-template-name }} \
            --attestation-data summary-${{ inputs.veracode-scan-results-file }}
        fi
